# Generated by Django 5.1.4 on 2024-12-07 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='descricao',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='descricao',
            field=models.CharField(max_length=280),
        ),
    ]
